【5.3.5.2　package_taskの例で異常終了する】

日付：　2016.04.05
現象：

以下のエラーメッセージが出力され、異常終了する。
	This application has requested the Runtime to terminate it in an unusual way.
	Please contact the application's support team for more information.

対策：
	スレッドを作成したcomp2関数から戻る前に、スレッドの終了を待つ
	処理を入れた

	// 2016.04.05 add
	t1.join(); t2.join();
	
	return f0.get() + f1.get();
	
	つまり、futureに対して、get()を呼び出すだけでは、スレッドの終了が
	保証できない模様

（追記）
日付：　2016.04.05
バージョン：　g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
現象：

Ubuntu環境では、以下のメッセージが出力される
	terminate called without an active exception

原因：
	threadオブジェクトが破壊されるときに、システムのスレッドが動作中であると、
	terminateを行う仕様となっている。
	この場合、f0.get() + f1.get()　によりタスクが終了してもシステムのスレッドが
	完了しておらず、この現象が現れるものと思われる。
	以下のように修正することができる。

		double res = f0.get() + f1.get();
		t1.join(); t2.join();
		return res;


【5.4.3　リテラル型：constexprメンバ関数にconst関数指定が必要】

日付：　2016.04.27
コメント：
	テキストの記述と異なり、constexprメンバ関数にもconst関数指定がが必要である
	
	struct Point {
		...
		//constexpr Point up(int d) { return {x, y, z+d}; }
		constexpr Point up(int d) const { return {x, y, z+d}; }
			// Invalid arguments 'Candidates are: Point up(int)	'
		...
	};
	
	constexpr Point p2 {p1.up(20)};

【5.6.2　complexの型変換のエラー】

日付：　2016.04.07
現象：
	スカラー型の異なるcomplex間の型変換と、complexとスカラー型の混合演算で
	エラーが出る
	

	complex<long double> ld {fl+sqrt(db)};
		↓
	no match for 'operator+' (operand types are 'std::complex<float>' and 'std::complex<double>')
	
	db += fl*3;
		↓
	no match for 'operator*' (operand types are 'std::complex<float>' and 'int')

	fl = pow(1/fl, 2);
		↓
	no match for 'operator/' (operand types are 'int' and 'std::complex<float>')

